<?php
/**
 * @file
 * Tonic brings some of Gin to the front end, such as the admin menu and
 * modal styles.
 */

if (file_exists(backdrop_get_path('theme', 'gin') . '/includes/shared.php')) {
  include_once(backdrop_get_path('theme', 'gin') . '/includes/shared.php');
}

/**
 * Implements hook_library_info_alter().
 *
 * Makes replacement of core admin_bar CSS with Gin's version more robust.
 */
function tonic_library_info_alter(&$libraries, $module) {
  $gin_activations = _tonic_gin_is_activated('all');
  if (!empty($gin_activations['gin'])) {
    include_once(backdrop_get_path('theme', 'gin') . '/includes/libraries.php');
    $libraries += gin_library_info();
  }
  // Update Admin Bar styles.
  if ($module == 'admin_bar' && isset($libraries['admin_bar']) && _tonic_gin_is_activated('admin_bar')) {
    $libraries['admin_bar']['css'] = array(
      backdrop_get_path('theme', 'gin') . '/dist/css/layout/gin_admin_bar.css' => [],
    );
  }
}

/**
 * Implements hook_preprocess_page().
 *
 * Add admin bar styles to the layout.
 */
function tonic_preprocess_page(&$variables) {
  $gin_activations = _tonic_gin_is_activated('all');
  if (!empty($gin_activations['gin'])) {
    if (function_exists('gin_add_module_libraries')) {
      gin_add_module_libraries();
    }
    $basethemeurl = backdrop_get_path('theme', 'gin');
    backdrop_add_library('gin', 'gin_init');
    backdrop_add_css($basethemeurl . '/dist/css/theme/font.css');
    backdrop_add_css($basethemeurl . '/dist/css/theme/variables.css');
    backdrop_add_css($basethemeurl . '/dist/css/theme/accent.css');
    if (!empty($gin_activations['admin_bar'])) {
      backdrop_add_library('gin', 'gin_admin_bar');
      if (config_get('admin_bar.settings', 'position_fixed')) {
        $variables['classes'][] = 'admin-bar--fixed';
      }
    }
    // @todo Make these optional?
    backdrop_add_library('gin', 'gin_dialog');
    if (module_exists('coffee')) {
      backdrop_add_library('gin', 'gin_coffee');
    }
    if (module_exists('ckeditor5')) {
      backdrop_add_library('gin', 'gin_ckeditor5');
    }

    $variables['html_classes'] = [];
    $basethemeurl = backdrop_get_path('theme', 'gin');

    // Darkmode.
    $darkmode_setting = theme_get_setting('enable_darkmode', 'gin');
    if (isset($darkmode_setting)) {
      $variables['html_classes'][] = 'gin--dark-mode';
      backdrop_add_html_head(
        [
          '#tag' => 'script',
          '#attributes' => [
            'type' => 'application/json',
            'id' => 'gin-setting-darkmode',
          ],
          '#value' => backdrop_json_encode(["ginDarkmode" => $darkmode_setting]),
        ],
        'gin_darkmode',
      );
    }

    // Set accent color.
    $variables['body_attributes']['data-gin-accent'] = theme_get_setting('preset_accent_color', 'gin');

    // Set focus color.
    $variables['body_attributes']['data-gin-focus'] = theme_get_setting('preset_focus_color', 'gin');

    // High contrast mode.
    if (theme_get_setting('high_contrast_mode', 'gin')) {
      $variables['classes'][] = 'gin--high-contrast-mode';
    }

    // Set layout density.
    $variables['body_attributes']['data-gin-layout-density'] = theme_get_setting('layout_density', 'gin');
    $variables['classes'][] = 'tonic--enabled';
    if (_tonic_gin_is_activated('simplei')) {
      backdrop_add_library('gin', 'gin_simplei');
    }
  }
}

/**
 * Helper function to see if Gin is activated but is not the current theme, and
 * optionally whether a particular feature is activated.
 *
 * @param string $feature
 *   The feature to check for. Defaults to 'gin'.
 *
 * @return array|bool
 *   If $feature is 'all', returns an array of all activated features. If
 *   $feature is a string, returns TRUE if the matching feature is activated,
 *   FALSE otherwise.
 */
function _tonic_gin_is_activated($feature = 'gin') {
  $activated = &backdrop_static(__FUNCTION__ . '_' . $GLOBALS['theme_key']);
  if (!isset($activated)) {
    $themes = list_themes();
    // First, see if Gin is activated, and make sure it's not the current theme.
    if ($themes['gin']->status && $GLOBALS['theme_key'] != 'gin') {
      $activated['gin'] = TRUE;

      // Check admin bar.
      // @todo: This should be a setting in the theme as an additional check.
      if (module_exists('admin_bar') && user_access('access administration bar')) {
        $activated['admin_bar'] = TRUE;

        if (module_exists('simplei')) {
          $activated['simplei'] = TRUE;
        }
      }
    }
    else {
      $activated['gin'] = FALSE;
    }
  }

  if ($feature == 'all') {
    return $activated;
  }
  else {
    return ($activated['gin'] && ($activated[$feature] ?? FALSE));
  }
}
